name: CI
on:
   workflow_dispatch:
     inputs:
       flavour:
         description: 'Flavour'
         required: true
         default: 'A1 Mercado'
jobs:

  Test:
    runs-on: self-hosted
    env:
      XC_VERSION: ${{ '12.5.1' }}
      XC_WorkSpace: ${{ 'Scarlet.xcworkspace' }}
      XC_SCHEME: ${{ github.event.inputs.flavour }}
    steps:
    - uses: actions/checkout@v1
    - name: List available Xcode versions
      run: ls /Applications | grep Xcode
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode.app
    - name: Pod De Integrate
      run: pod deintegrate
    - name: Pod Run
      run: pod install
    - name: Run unit tests
      run: xcodebuild test -scheme Scarlet -workspace "$XC_WorkSpace" -destination 'platform=iOS Simulator,name=iPhone 11,OS=14.5' | xcpretty && exit ${PIPESTATUS[0]}

        
